cmake_minimum_required(VERSION 3.18)
project(straw_matlab LANGUAGES CXX)
find_package(Matlab REQUIRED COMPONENTS MX_LIBRARY MEX_COMPILER)
if(NOT TARGET straw_c_api)
  find_package(straw 1 REQUIRED CONFIG)
  set(STRAW_MATLAB_LIBRARY straw::straw)
else()
  set(STRAW_MATLAB_LIBRARY straw_c_api)
endif()
matlab_add_mex(NAME straw_mex SRC straw_mex.cpp LINK_TO ${STRAW_MATLAB_LIBRARY})
target_compile_features(straw_mex PRIVATE cxx_std_14)
